/*
 * This source file was generated by the Gradle 'init' task
 */
package tp;

import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.image.*;
import javafx.scene.input.MouseButton;
import javafx.scene.layout.*;
import javafx.scene.shape.Circle;
import javafx.scene.text.Text;
import javafx.stage.FileChooser;
import javafx.stage.Modality;
import javafx.stage.Stage;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class AppTest extends Application {
    private String nickName = "sangyan_";
    private String fullName = "Sang Yan";
    private Image profileImage = new Image("file:default-profile.png");

    private final List<Post> posts = new ArrayList<>();
    private final GridPane postGrid = new GridPane();

    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("MyMoment");

        // Profile section
        ImageView profileImageView = new ImageView(profileImage);
        profileImageView.setFitHeight(100);
        profileImageView.setFitWidth(100);
        profileImageView.setClip(new Circle(50, 50, 50));

        VBox profileBox = new VBox(profileImageView);
        profileBox.setAlignment(Pos.CENTER_LEFT);
        profileBox.setPadding(new Insets(10));

        VBox nameBox = new VBox(
                new Label(nickName),
                new Label(fullName)
        );
        nameBox.setAlignment(Pos.CENTER_LEFT);
        nameBox.setPadding(new Insets(10));

        Button addPostButton = new Button("Add Post");
        addPostButton.setOnAction(e -> showAddPostWindow());

        HBox topBar = new HBox(profileBox, nameBox, addPostButton);
        topBar.setSpacing(20);
        topBar.setPadding(new Insets(10));
        topBar.setAlignment(Pos.CENTER_LEFT);

        // Post section
        postGrid.setHgap(10);
        postGrid.setVgap(10);
        postGrid.setPadding(new Insets(10));

        ScrollPane scrollPane = new ScrollPane(postGrid);
        scrollPane.setFitToWidth(true);

        VBox mainLayout = new VBox(topBar, scrollPane);
        Scene scene = new Scene(mainLayout, 800, 600);

        primaryStage.setScene(scene);
        primaryStage.show();
    }

    private void showAddPostWindow() {
        Stage postStage = new Stage();
        postStage.initModality(Modality.APPLICATION_MODAL);
        postStage.setTitle("New Post");

        ImageView preview = new ImageView();
        preview.setFitWidth(300);
        preview.setPreserveRatio(true);

        TextField captionField = new TextField();
        captionField.setPromptText("Enter caption...");

        Button uploadButton = new Button("Upload Image");
        FileChooser fileChooser = new FileChooser();
        final File[] selectedFile = new File[1];

        uploadButton.setOnAction(e -> {
            selectedFile[0] = fileChooser.showOpenDialog(postStage);
            if (selectedFile[0] != null) {
                preview.setImage(new Image(selectedFile[0].toURI().toString()));
            }
        });

        Button submitButton = new Button("Submit Post");
        submitButton.setOnAction(e -> {
            if (selectedFile[0] != null) {
                Post newPost = new Post(captionField.getText(), new Image(selectedFile[0].toURI().toString()));
                posts.add(newPost);
                updatePostGrid();
                postStage.close();
            }
        });

        VBox layout = new VBox(uploadButton, preview, captionField, submitButton);
        layout.setSpacing(10);
        layout.setPadding(new Insets(10));
        layout.setAlignment(Pos.CENTER);

        Scene scene = new Scene(layout, 350, 500);
        postStage.setScene(scene);
        postStage.show();
    }

    private void updatePostGrid() {
        postGrid.getChildren().clear();
        int col = 0;
        int row = 0;

        for (Post post : posts) {
            StackPane postContainer = createImageContainer(post);
            postGrid.add(postContainer, col, row);
            col++;
            if (col == 3) {
                col = 0;
                row++;
            }
        }
    }

    private StackPane createImageContainer(Post post) {
        ImageView imageView = new ImageView(post.postImage);
        imageView.setFitWidth(200);
        imageView.setPreserveRatio(true);

        Label captionLabel = new Label(post.caption);
        captionLabel.setStyle("-fx-background-color: rgba(0,0,0,0.5); -fx-text-fill: white; -fx-padding: 5px;");
        captionLabel.setVisible(false);

        StackPane container = new StackPane(imageView, captionLabel);
        container.setOnMouseEntered(e -> {
            container.setScaleX(1.05);
            container.setScaleY(1.05);
            captionLabel.setVisible(true);
        });
        container.setOnMouseExited(e -> {
            container.setScaleX(1);
            container.setScaleY(1);
            captionLabel.setVisible(false);
        });
        container.setOnMouseClicked(e -> {
            if (e.getButton() == MouseButton.PRIMARY && e.getClickCount() == 2) {
                Stage previewStage = new Stage();
                ImageView preview = new ImageView(post.postImage);
                preview.setPreserveRatio(true);
                preview.setFitWidth(500);
                Scene previewScene = new Scene(new StackPane(preview), 520, 520);
                previewStage.setScene(previewScene);
                previewStage.setTitle("Post Preview");
                previewStage.show();
            }
        });

        return container;
    }

    public static void main(String[] args) {
        launch(args);
    }

    static class Post {
        String caption;
        Image postImage;

        Post(String caption, Image postImage) {
            this.caption = caption;
            this.postImage = postImage;
        }
    }
}

