/*
 * This source file was generated by the Gradle 'init' task
 */
package tp9;

import javafx.application.Application; 
import javafx.stage.Stage; 
import javafx.scene.Scene;
import javafx.scene.layout.HBox;

public class App extends Application{
    public void start(Stage primaryStage)
    { 
        // Inisialisasi Stage 
        primaryStage.setTitle("My JavaFX App");
        HBox root = new HBox();

        // Inisialisasi Scene 
        Scene scene = new Scene(root, 400, 300);

        // Menambahkan Scene ke dalam Stage 
        primaryStage.setScene(scene); 
        
        // Menampilkan Stage 
        primaryStage.show(); 
    } 
    public static void main(String[] args) { 
        launch(args);
        }
}